import logging

# configuring logger
logging.basicConfig(format='%(asctime)s %(filename)s %(threadName)s %(message)s ')
logger = logging.getLogger()
logger.setLevel(logging.DEBUG)

# Enter machine name / host name
# update hostname printed by the server
# for the client
# HOST = 'elnux3.cs.umass.edu'
HOST = "127.0.0.1"

 # Specify the port to connect to
PORT = 51312

NUM_OF_THREADS = 3

stocksDB = {"GameStart": {"price": 14.96,"volume":0 ,"limit": 100},
                "FishCo": {"price": 17.99, "volume":0 ,"limit": 45}}

# number of total request to be generated by the client
QUERYCOUNT = 500